### ISSUE TITLE
The remote search of dropdown cannot be realized

### ISSUE THREAD

**Issue by happy2091366** [killkli/vue3_jspreadsheet#4]
code:
setup() {
			const mysheetdata = ref([]);
			const myOption = ref({
				columns: [{
						type: "dropdown",
						title: "物料编号",
						name: 'item_code',
						width: "260px",
						url: 'http://gerp.gracemes.com/api/newfile.qua',
						remoteSearch: true,
						autocomplete: true,
						lazyLoading: true,
					},
					{
						type: "text",
						title: "物料名称",
						name: 'item_name',
						width: "160px",
						readOnly: true
					},
......

**Comment by killkli** [comment]
I'll look into this as soon as possible/

**Comment by happy2091366** [comment]
Thank you very much for your reply!!!

**Comment by killkli** [comment]
Hello~ I've look into the code of original JSpreadsheetCE ver. Although the dropdown was an implementation of JSuite, however, it's not a full implementation. The remotesearch option is not supported  in JSpreadsheetCE. I can try to modify JSpreadsheetCE to support the function, but this will modify JSpreadsheetCE itself, which IMO is better ask JSpreadsheetCE for support >_<

JSpreadsheet's repo is here:
https://github.com/jspreadsheet/ce

**Comment by happy2091366** [comment]
ok! Thank you very much  !
